### ISSUE TITLE
[BUG] Icons of shortcuts not displayed correctly

### ISSUE THREAD

**Issue by jonaskohl** [Hofknecht/SystemTrayMenu#209] opened 2021-10-07 11:02 UTC
Icons of shortcuts do not get displayed correctly. This is the log file:

```
2021.10.07 10:56:22.308 1  INFO Application Start SystemTrayMenu.dll | 1.0.20.0 | ScalingFactor=1
2021.10.07 10:56:30.666 1  WARN Dgv_DataError occured System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Icon'.    at System.Drawing.Icon.get_Handle()    at System.Drawing.Icon.get_Size()    at System.Drawing.Icon.BmpFrame()    at System.Drawing.Icon.ToBitmap()    at System.Drawing.IconConverter.ConvertTo(ITypeDescriptorContext context, CultureInfo culture, Object value, Type destinationType)    at System.Windows.Forms.Formatter.FormatObjectInternal(Object value, Type targetType, TypeConverter sourceConverter, TypeConverter targetConverter, String formatString, IFormatProvider formatInfo, Object formattedNullValue)    at System.Windows.Forms.Formatter.FormatObject(Object value, Type targetType, TypeConverter sourceConverter, TypeConverter targetConverter, String formatString, IFormatProvider formatInfo, Object formattedNullValue, Object dataSourceNullValue)    at System.Windows.Forms.DataGridViewCell.GetFormattedValue(Object value, Int32 rowIndex, DataGridViewCellStyle& cellStyle, TypeConverter valueTypeConverter, TypeConverter formattedValueTypeConverter, DataGridViewDataErrorContexts context)
```

Screenshot:
![image](https://user-images.githubusercontent.com/23175424/136371980-691dbd7b-c43b-44fe-aa0b-d5a6b9220759.png)

 - OS: Windows 10 Pro 21H1
 - Version 1.0.20.0

**Comment by Hofknecht** [comment] 2021-10-07 18:05
@jonaskohl Thank you for the feedback!

The warning is related to
[BUG] DataError Event DataGridView #186
there we only suppressed it because i could only reproduce it rare times, i made a comment there that i could reproduce with:
when focused and close other application => closed and activated at same time

Do you remember how you reproduced it? by this behavior or do you have any hints to reproduce?
Is it really occur rare times and is most times shown correctly? (only to make sure it is really related to #186)

**Comment by Hofknecht** [comment] 2021-10-10 16:29
@jonaskohl 
please try latest version and reopen the issue if still not working
Thank you!

**Comment by Hofknecht** [comment] 2021-10-13 15:44
@jonaskohl  Thank you!
i think i found the issue, can you please try version 1.0.21.3
[SystemTrayMenu-1.0.21.3.zip](https://github.com/Hofknecht/SystemTrayMenu/files/7339645/SystemTrayMenu-1.0.21.3.zip)

will be in next release 1.0.22

i will close again, please reopen if issue not solved

**Closed by Hofknecht** 2021-10-13 15:44 UTC
Labels: low prio
