### ISSUE TITLE
[BUG] Mouse Over Folder Expand 

### ISSUE THREAD

**Issue by RobersonIns** [Hofknecht/SystemTrayMenu#381] opened 2022-05-18 15:51 UTC
I have two users on one PC. The mouse over folder expand works for one user but not the other. Both are set as admins with the same permissions on the pc. Everything else works perfectly.

User 1
![STM01](https://user-images.githubusercontent.com/105805227/169086477-2511732d-a690-4130-89f1-022d533c15b1.jpg)

User 2
![STM02](https://user-images.githubusercontent.com/105805227/169086519-7c73ca58-6cd0-424d-8ac6-9f7208087b77.jpg)

 - OS: Microsoft Windows 11 Pro
 - Version: 21H2
 - OS Build: 22000.675

**Comment by Hofknecht** [comment] 2022-05-24 18:27
@RobersonIns 
Thank you for the feedback!

Unfortunately we haven't been able to reproduce it yet.

we have a couple of questions:

1. Is it only when you hover over it via mouse? So as a counter-test, search for "Forms" in the search textbox and then press 'Enter' and maybe second test try select it with the arrow keys.

2. Does it only affect certain folders? Maybe you can create an empty folder and try it with this one?
![2022-05-24 20_21_08-](https://user-images.githubusercontent.com/52528841/170105310-8ac26953-9cba-41ef-b421-312943ddf64d.png)

3. Does it have to do with whether the first user is logged in? So if e.g. only your second user is logged in after a restart, does it work then? and are both users logged in at the same time?

4. If the data cannot be loaded almost immediately, a loading menu appears. 
![2022-05-24 19_43_12-](https://user-images.githubusercontent.com/52528841/170098986-dffe1d67-cbe2-4a42-b6f8-6deb62f0f7ab.png)
Does this appear on your second user?
(if data takes longer it would not disappear until the data is loaded)

5. if access is denied via permissions, then such a submenu appears 'Folder inaccesable'
![2022-05-24 19_51_32-](https://user-images.githubusercontent.com/52528841/170101022-68639592-16ea-4d42-b1f0-8458dd0412af.png)
Does this appear on your second user?

6. By switching to the other user, the App is restarted. But does it possibly make a difference if you restart the STM on the second user?

7. This restart would be visible in the log file with correct timestamp. Are there messages since this restart that could help us? (You can / should remove all user specific paths). Maybe something like?
Application Start SystemTrayMenu.dll | 1.2.8.1 | ScalingFactor=1,25
2022.02.19 08:42:46.344 24  WARN shortcutFilename:'C:\Progr....\...ices.lnk' System.UnauthorizedAccessException: Access is denied. (0x80070005 (E_ACCESSDENIED))    at Shell32.FolderItem.get_GetLink()    at SystemTrayMenu.Utilities.FileLnk.GetShortcutFileNamePath(Object shortcutFilename, Boolean& isFolder) in D:\....\C#Projects\systemtraymenu\Utilities\File\FileLnk.cs:line 61
if not clear you can send me also complete logfile to mail Markus@Hofknecht.eu
Find the logfile via right click at contextmenu -> 'Log File'

8. Maybe you can make a video of the behavior, therefore i would recommend 'Apowersoft Free Screen Recorder'

**Comment by Hofknecht** [comment] 2022-06-05 09:04
@RobersonIns
Maybe one of the questions helped to solve the problem?
We're closing the issue for now, if it happens again, feel free to reopen the issue.

**Comment by RobersonIns** [comment] 2022-06-14 17:11
Sorry for the slow reply. I didn't get notified of your reply.
1. Yes, it is only the mouse hover. Everything else works as it should. 
2. It effects all folders. 
3. Only one user logged in at a time. 
4. no loading message. 
5. both users have admin rights with no folder restrictions. 
6. restarting stm does not help. 
7. let me know if you want the log files for the two users. 
8. videos attached

https://user-images.githubusercontent.com/105805227/173636514-86bf0875-af0d-4ebe-8934-ea837fb86e65.mp4


https://user-images.githubusercontent.com/105805227/173636518-e93b1daf-90b8-4371-8450-bc132a7267b1.mp4

**Comment by Hofknecht** [comment] 2022-06-23 19:14
@RobersonIns 
Many thanks for your support, especially for answering the questions! Unfortunately I still can't reproduce it. The log file would be very interesting, it would be great if you could send it to us to mail Markus@Hofknecht.eu

(In principle, the app is only possible in one instance, i.e. only with one user at a time, but that's not the problem here, since the app starts.)

Let's hope that we can find something in the log file, otherwise I'll have to think again

**Comment by Hofknecht** [comment] 2022-07-10 13:50
@RobersonIns 

> let me know if you want the log files for the two users.

yes logfile would be great.
I think in the log file we should find an exception, probably some rights problems, so that the STM cannot resolve the folders. We can't reproduce it.

If nothing could be seen in the log file, it would be great if you could debug the situation with visual studio at the user where it is not working from.

somewhere here:
internal static MenuData GetData(BackgroundWorker worker, string path, int level)

or here:
![2022-07-10 15_48_21-Window](https://user-images.githubusercontent.com/52528841/178147640-f1255d56-59be-43ef-8a3e-1d519e6f0b92.png)

We're closing the issue for now, if you send the logfile, feel free to reopen the issue.

**Closed by Hofknecht** 2022-07-10 13:50 UTC
Labels: help wanted, FAQ
